openapi: 3.0.4
info:
  title: Last Race API
  version: 1.0.0
  description: API for the WA1 Last Race exam assignment

servers:
  - url: http://localhost:3001/api

components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: connect.sid

  schemas:
    Game:
      type: object
      description: Game schema
      properties:
        gameId: 
          type: integer
        player:
          type: string
        currentCredits: 
          type: integer
        startedAt:
          type: string

    User:
      type: object
      description: User schema
      properties:
        username:
          type: string
        playedGames:
          type: integer
        bestResult: 
          type: integer

    Event:
      type: object
      description: Event schema
      properties:
        eventId:
          type: string
        description:
          type: string
        effect:
          type: integer

    Station:
      type: object
      description: Stations schme
      properties:
        stationName:
          type: string
        neighbourStations:
          type: array
          items:
            $ref: '#/components/schemas/Station'
        interchangeStation:
          type: boolean

    Line:
      type: object
      properties:
        name:
          type: string
        stations:
          type: array
          items: 
            $ref: '#/components/schemas/Station'

paths:
  # Authentication
  /auth/login:
    post:
      summary: Login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [studentId, password]
              properties:
                studentId:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /auth/logout:
    post:
      summary: Logout
      tags: [Auth]
      responses:
        '200':
          description: Logged out successfully

  /auth/current:
    get:
      summary: Get current logged-in user
      tags: [Auth]
      responses:
        '200':
          description: Current user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Not authenticated

  # User
  /user:
    post:
      summary: Register new user
      tags: [User]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Student registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '409':
          description: Username already exists

  /users/{username}:
    get:
      summary: Get username details (own only)
      tags: [User]
      security:
        - sessionCookie: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema:
                    $ref: '#/components/schemas/User'